# Generated by Django 5.1.1 on 2024-09-21 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Tecnologia', 'Tecnología'), ('Educacion', 'Educación'), ('Salud', 'Salud'), ('Alimentacion', 'Alimentación')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=20)),
                ('descripcion', models.TextField()),
                ('disponibilidadhoraria', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imgservices/')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='imgavatar/predeterminado.jpg', upload_to='imgavatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
